### ISSUE TITLE
org.eclipse.egit.github.core/4.10.0.201712302008-r missing from maven

### ISSUE THREAD

**Issue by parsnips** [eclipse-egit/egit#20]
### Version

4.10.0

### Operating System

Linux/Unix, MacOS, Windows

### Eclipse version

n/a

### Bug description

Building a project with bazel rules_jvm_external fails when downloading deps, we find that `org.eclipse.egit.github.core` no longer exists.

```
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/mnt/data/root/.cache/bazel/_bazel_root/b7c0e49dc48477b0008fee9f624522db/external/rules_jvm_external/coursier.bzl", line 852, column 38, in _coursier_fetch_impl
		dep_tree = make_coursier_dep_tree(
	File "/mnt/data/root/.cache/bazel/_bazel_root/b7c0e49dc48477b0008fee9f624522db/external/rules_jvm_external/coursier.bzl", line 783, column 13, in make_coursier_dep_tree
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Resolution error: Error downloading org.eclipse.mylyn.github:org.eclipse.egit.github.core:4.10.0.201712302008-r
  not found: https://maven.google.com/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.pom
  not found: https://repo1.maven.org/maven2/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.pom
  not found: https://s3-us-west-2.amazonaws.com/dynamodb-local/release/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.pom
  forbidden: https://repo.eclipse.org/content/groups/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.pom
```

### Actual behavior

The library is not downloadable at any existing repository.

### Expected behavior

It should download at existing repositories or redirect to new ones.

**Comment by msohn** [comment]
AFAICS this old library version is available for download under
https://repo.eclipse.org/content/groups/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/
the jar file is here https://repo.eclipse.org/content/groups/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.jar
