### ISSUE TITLE
Setting up external diff tool triggers error "'Running external diff toool...' has encountered a problem."

### ISSUE THREAD

**Issue by StefanHISE** [eclipse-egit/egit#42]
### Version

6.8.0

### Operating System

Windows

### Eclipse version

2023-12

### Bug description

In Eclipse under Preferences -> Version Control (Team) -> Git -> Diff/Merge -> enable 'Use external tool if configured by git or product' as shown in the following screenshot:

![image](https://github.com/eclipse-egit/egit/assets/106373698/00b2ab84-234f-4083-86ec-e5b2737fe6c5)

In my user .gitconfig configuration file I've added two entries to set Winmerge as the merge and diff tool:
![image](https://github.com/eclipse-egit/egit/assets/106373698/918d586c-23cc-4006-8cc8-76c4dfd5e116)

In Eclipse double click an item with some changes in the 'Git Staging' tab to bring up the file diff.

### Actual behavior

The following error popup shows up:
![image](https://github.com/eclipse-egit/egit/assets/106373698/77471a15-6831-4af5-aa96-8063d9556314)

### Expected behavior

Winmerge is opened, showing the diff of the selected file.

Alternatively, if there indeed is something wrong with the configuration, a more meaningful error message would be useful 'Index 1 out of bounds for length 1' doesn't really tell me much without looking into the eGit source-code.

### Other information

Could this be related to this bug in the old bug tracker? https://bugs.eclipse.org/bugs/show_bug.cgi?id=580088
At least in comment 8, it seems to me that some special handling might be needed to support some of the default config settings which might not have been impleted yet in EGit: https://bugs.eclipse.org/bugs/show_bug.cgi?id=580088#c8

**Comment by PeterLindgren-se** [comment]
I recently encountered the same problem, I have a difftool and guitool specified to a third-party tool. It has worked before (at least 2 weeks before today), and the third-party tool is not changed (still works with other tools).

Eclipse 2025.06, EGit 7.3.0, Windows 11 23H2. The .metadata/.log file shows the following error log:

```
!ENTRY org.eclipse.core.jobs 4 2 2025-10-03 11:27:54.627
!MESSAGE An internal error occurred during: "Running external diff tool...".
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.egit.ui.internal.diffmerge.DiffMergeSettings.getDiffToolCommandFromPreferences(DiffMergeSettings.java:276)
	at org.eclipse.egit.ui.internal.CompareUtils$1.run(CompareUtils.java:420)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Looking at the code, it seems like the call to getExternalDiffToolPreference() returns an empty string at DiffMergeSettings.java#L272 and the code comments for getExternalDiffToolPreference() states that it might return an empty string if the preference is not set.

I'm not well versed in neither Eclipse nor EGit code base, so I'm not sure why getExternalDiffToolPreference() returns empty string.
Here are excerpt from my .gitconfig:
```
[diff]
	guitool = beyondcompare4
	tool = beyondcompare4
[difftool "beyondcompare4"]
	path = \"c:/Users/XXXXXX/AppData/Local/Beyond Compare 4/bcomp.exe\"
	cmd = \"c:/Users/XXXXXX/AppData/Local/Beyond Compare 4/bcomp.exe\" \"$LOCAL\" \"$REMOTE\"
[difftool]
	prompt = true
```
