### ISSUE TITLE
AbstractGitCompareEditorInput: ClassCastException

### ISSUE THREAD

**Issue by jukzi** [eclipse-egit/egit#56]
### Version

6.7.0

### Operating System

Windows

### Eclipse version

4.29.0.I20230903-1000

### Bug description

```
java.lang.ClassCastException: Cannot cast org.eclipse.ui.part.ShowInContext to org.eclipse.ui.part.IShowInSource
	at org.eclipse.egit.ui.internal.merge.AbstractGitCompareEditorInput.getAdapter(AbstractGitCompareEditorInput.java:149)
```

### Actual behavior

During a merge opening the preferences dialog triggered a Error-Popup showed up. Upon confirming "OK" it just poped up again. and again.. eclipse had to be terminated. After restart the error was visible in the error log view
![image](https://github.com/user-attachments/assets/422fd1ea-03ea-4598-89d8-e49d86234b97)

### Expected behavior

no ClassCastException

### Relevant log output

```Shell
eclipse.buildId=4.29.0.I20230903-1000

java.version=17.0.9

java.vendor=Eclipse Adoptium

BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US

Command-line arguments:  -os win32 -ws win32 -arch x86_64
 
This is a continuation of log file C:\WAMAS\WAMAS-IDE-5_19\.metadata\.bak_1.log

Created Time: 2024-09-10 08:52:08.398
 
org.eclipse.ui.workbench

Error

Tue Sep 10 08:52:29 CEST 2024

Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
 
java.lang.ClassCastException: Cannot cast org.eclipse.ui.part.ShowInContext to org.eclipse.ui.part.IShowInSource

	at java.base/java.lang.Class.cast(Class.java:3889)

	at org.eclipse.egit.ui.internal.merge.AbstractGitCompareEditorInput.getAdapter(AbstractGitCompareEditorInput.java:149)

	at org.eclipse.core.runtime.Adapters.adapt(Adapters.java:67)

	at org.eclipse.core.runtime.Adapters.adapt(Adapters.java:116)

	at org.eclipse.compare.internal.CompareEditor.getAdapter(CompareEditor.java:196)

	at org.eclipse.core.runtime.Adapters.adapt(Adapters.java:67)

	at org.eclipse.core.runtime.Adapters.adapt(Adapters.java:116)

	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.getShowInSource(WorkbenchSourceProvider.java:386)

	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.getContext(WorkbenchSourceProvider.java:390)

	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.updateActivePart(WorkbenchSourceProvider.java:444)

	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.checkActivePart(WorkbenchSourceProvider.java:282)

	at org.eclipse.ui.internal.services.WorkbenchSourceProvider.checkActivePart(WorkbenchSourceProvider.java:277)

	at org.eclipse.ui.internal.services.WorkbenchSourceProvider$1.partBroughtToTop(WorkbenchSourceProvider.java:212)

	at org.eclipse.ui.internal.PartService$2.run(PartService.java:97)

	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

	at org.eclipse.ui.internal.PartService.partBroughtToTop(PartService.java:94)

	at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:5132)

	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

	at org.eclipse.ui.internal.WorkbenchPage.firePartBroughtToTop(WorkbenchPage.java:5129)

	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partBroughtToTop(WorkbenchPage.java:221)

	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$6.run(PartServiceImpl.java:314)

	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartBroughtToTop(PartServiceImpl.java:311)

	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:107)

	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)

	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)

	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)

	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)

	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)

	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)

	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)

	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)

	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)

	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)

	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)

	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)

	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)

	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)

	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)

	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)

	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)

	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1390)

	at org.eclipse.ui.internal.WorkbenchPage.hidePart(WorkbenchPage.java:1543)

	at org.eclipse.ui.internal.WorkbenchPage.closeEditor(WorkbenchPage.java:1483)

	at org.eclipse.ui.internal.Workbench$12.run(Workbench.java:1162)

	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

	at org.eclipse.ui.internal.Workbench.persist(Workbench.java:1145)

	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:1086)

	at org.eclipse.ui.internal.Workbench.lambda$4(Workbench.java:1393)

	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)

	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1393)

	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1369)

	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:1717)

	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:1744)

	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)

	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:1744)

	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:1753)

	at org.eclipse.ui.internal.WorkbenchWindow.lambda$2(WorkbenchWindow.java:504)

	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.lambda$4(WBWRenderer.java:570)

	at org.eclipse.swt.events.ShellListener$2.shellClosed(ShellListener.java:102)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:102)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)

	at org.eclipse.swt.widgets.Decorations.closeWidget(Decorations.java:269)

	at org.eclipse.swt.widgets.Decorations.WM_CLOSE(Decorations.java:1550)

	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4746)

	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)

	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1478)

	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2306)

	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5040)

	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)

	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:508)

	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4845)

	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)

	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1478)

	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2306)

	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5040)

	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)

	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:508)

	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4845)

	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)

	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1478)

	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2306)

	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5040)

	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3658)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)

	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)

	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)

	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)

	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```

**Comment by tomaswolf** [comment]
[Gerrit 1200943](https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1200943) should fix this.

**Comment by tomaswolf** [comment]
[Gerrit 1200943](https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1200943) is merged.
